apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boardgame-pvc
  namespace: demoapp-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3   # IMPORTANT
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: demoapp-dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: 073107684180.dkr.ecr.ap-south-1.amazonaws.com/data_oceano/devlop_env:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"      # 0.25 CPU
              memory: "512Mi"  # minimum required
            limits:
              cpu: "500m"      # max 0.5 CPU
              memory: "1Gi"    # max RAM
          volumeMounts:
            - name: boardgame-storage
              mountPath: /app/data
      volumes:
        - name: boardgame-storage
          persistentVolumeClaim:
            claimName: boardgame-pvc
